
- template:
     src: '{{ docker_value }}'
     dest: /etc/lamp_Dockerfile
     mode: 0644
     owner: root
     group: root

#login in dockerhub
- name: docker login
  docker_login:
    username: '{{ docker_login_username }}'
    password: '{{ docker_login_password }}'
    reauthorize: yes

# - name: Build an image and push it to a private repo
#   docker_image:
#     path: /etc/
#     name: '{{ docker_repository_name }}/{{ docker_image_name }}'
#     tag: latest
#     push: yes

- name: pull an image
  docker_image:
    name: '{{ docker_repository_name }}/{{ docker_image_name }}'
 
- name: run helloworld file
  template:
    src: helloworld.html
    dest: /var/www/html/helloworld.html

- name: Permission 
  shell: chmod +x /var/www/html/helloworld.html

 