
- include_tasks: setup-Debian.yml

# - name: To check old version of docker is not installed
#   package: 
#     name:
#       - docker
#       - docker-engine
#     state: absent 

# - name: Ensure dependencies are installed.
#   apt:
#     name:
#       - apt-transport-https
#       - ca-certificates
#     state: present

# - name: Add Docker apt-key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
#     state: present