
- name: install apache2
  apt: name=apache2 state=latest

- name: install php module for apache2
  apt: name=php state=latest
  
- name: Start apache2
  service:
    name=apache2
    state=started
    enabled=yes

- name: install hello world html script
  copy: src=hello.html dest=/var/www/html/hello.html mode=0664

